### ISSUE TITLE
希望能够直接调用开源弹幕库

### ISSUE THREAD

**Issue by Seifon** [danielwii/flutter_barrage#1]
在IOS和Android都有比较优秀的高性能框架。希望能考虑通过channel调用原生

IOS：https://github.com/unash/BarrageRenderer

Android：https://github.com/bilibili/DanmakuFlameMaster

**Comment by danielwii** [comment]
hi，感谢您注意到该项目。
flutter_barrage 计划中将完全使用 flutter 来实现，所以暂时可能不会考虑调用其他原生实现。

**Comment by Seifon** [comment]
那也行，我的项目就用您的插件了。希望您越做越好，提高弹幕的性能。另外，希望能加入调整透明度，数量，位置，弹幕速度等功能额

**Comment by danielwii** [comment]
感谢使用，目前测试的时候是使用了每分钟 1000 条弹幕，但是观测性能的时候似乎有极小的卡顿现象。
另外由于接口中的弹幕使用的是自己传入的 widget，所以相当于提供了弹幕自定义的能力，您可以直接将透明度加入到 widget 中。
```dart
Bullet(
    child: Container(
        decoration: BoxDecoration(color: Colors.black.withOpacity(.2)),
        padding: EdgeInsets.symmetric(horizontal: 6),
        child: Text(text)))
```
另外 BarrageWall 有个 int speed 的参数是用来调整速度的，其值除以 2 等于在可见区域出现的时间。
不过目前是所有弹幕共享的速度，如果需要单独弹幕速度调整的话可以在下个版本中实现。
另外我会将示例和文档更加完善。
目前弹幕出现的位置是获取 BarrageWall 的高度随机出现的，确实可能会出现覆盖的问题，也计划在下个版本中改进。
PS：再次感谢您的使用，如果喜欢该插件，欢迎 star。
