### ISSUE TITLE
弹幕发射一段时间后，会清理并释放资源吗？

### ISSUE THREAD

**Issue by Seifon** [danielwii/flutter_barrage#10]
加了弹幕，感觉有点变卡了。不知道send弹幕，积攒到了一定数量有没有清理和释放资源呢？

**Comment by danielwii** [comment]
你的同屏弹幕和弹幕总数有多少？
动画完成后弹幕会返回一个 `const SizedBox();`。
目前没有采用其他方式释放弹幕，之前发现在主动调用释放的时候会有明显的卡顿。

**Comment by Seifon** [comment]
有时候30、40左右吧，最多的时候基本是满屏幕弹幕。弹幕刚开始不卡，到后面越来越卡。如果能够到达一定数量，清理历史弹幕就好了

**Comment by danielwii** [comment]
之前测试过，回收资源的时候会有明显的卡顿。
你可以把弹幕数量和时长发给我，之后我再测试下。

**Comment by Seifon** [comment]
回收频率可以高点，这样回收资源的量会少一点

**Comment by Seifon** [comment]
数量就是30-40，时长：1小时左右

**Comment by Seifon** [comment]
这个问题，有用户也向我反馈了。目前关掉send入口，就不会卡。估计是到一定时间，由于没有释放资源，导致send弹幕变卡的

**Comment by Seifon** [comment]
目前这个插件的功能基本都已经有了，希望后面能够专门针对性能这一块做一下优化

**Comment by danielwii** [comment]
目前发布了 `v0.4.1`，重新打开了 cleaner。
并且增加了内置的打开关闭弹幕功能。
