### ISSUE TITLE
barrageWallController.send 只在第一次生效

### ISSUE THREAD

**Issue by ietf626** [danielwii/flutter_barrage#11]
barrageWallController.send([new Bullet(child: Text(text))]);
send方法只在第一次生效，之后再调用时就不生效了，我的初始bullets传入的是空数组。
期待楼主回复。

**Comment by danielwii** [comment]
Hi @ietf626 ，非常感谢您使用该插件。
我测试了一下，确实存在这样的 bug，并且在空数组的时候直接触发了。
我发布了 [v0.3.3](https://pub.dev/packages/flutter_barrage/versions/0.3.3)，并在 examples 测试了该场景，希望能解决你的问题。
