### ISSUE TITLE
0.4.2 版，只能发一次弹幕

### ISSUE THREAD

**Issue by coooooof** [danielwii/flutter_barrage#12]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

• No issues found!

插件版本 0.4.2

发送弹幕
`
  _barrageWallController.send([
     Bullet(
       child: bullet(context, message),
      ),
   ]);
   _textEditingController.clear();
`

只能发一次弹幕，后续发弹幕就不出现了

**Comment by danielwii** [comment]
你好，我测试了一下 examples 和我自己的应用，都没有遇到这个情况。
你可以简历一个仓库 reproduce 一下这个场景，我可以上去看看。

**Comment by coooooof** [comment]
> 你好，我测试了一下 examples 和我自己的应用，都没有遇到这个情况。
> 你可以建立一个仓库 reproduce 一下这个场景，我可以上去看看。

[https://github.com/coooooof/flutter_barrage](url)

**Comment by coooooof** [comment]
> 你好，我测试了一下 examples 和我自己的应用，都没有遇到这个情况。
> 你可以建立一个仓库 reproduce 一下这个场景，我可以上去看看。

[https://github.com/coooooof/flutter_barrage.git](https://github.com/coooooof/flutter_barrage.git)

**Comment by coooooof** [comment]
> 你好，我测试了一下 examples 和我自己的应用，都没有遇到这个情况。
> 你可以建立一个仓库 reproduce 一下这个场景，我可以上去看看。

基本上 debug 或者 release 模式第一次进应用后会出现此 bug,
如果 debug 模式下 reload 一下才能正常使用，但是 release 不存在reload

**Comment by danielwii** [comment]
@coooooof 非常抱歉，我在测试的时候只测试了 chewie 的，确实存在这个问题。你可以使用
```
flutter_barrage:
    git:
      url: git://github.com/danielwii/flutter_barrage.git
      ref: feature/fix-#12
```
测试是否修复，稍后我会发 0.4.3。

**Comment by danielwii** [comment]
0.4.3 has released.
