### ISSUE TITLE
能否动态加载bullets

### ISSUE THREAD

**Issue by zzAbel** [danielwii/flutter_barrage#14]
想根据时间段从服务端请求弹幕数据并添加到弹幕列表中，目前发现修改bullets并setState 仍然不会展现

**Comment by danielwii** [comment]
试试通过
```dart
barrageWallController.value.bullets.appendByMinutes(bullets);
```
可以实现吗？

**Comment by EdmodoYunjiang** [comment]
![image](https://user-images.githubusercontent.com/54974019/103927207-f1c11e00-5154-11eb-9f3f-9984934b77b8.png)

不行，这里的size并不会改变 processed也增加到跟size一样就停止了。

**Comment by danielwii** [comment]
感谢反馈，我尝试新增个方法来解决这个问题。

**Comment by EdmodoYunjiang** [comment]
这里还有个问题，这里的`maxBulletHeight`是否应该是int类型，或者下面的`_maxBulletHeight`是double类型
![image](https://user-images.githubusercontent.com/54974019/103929514-621d6e80-5158-11eb-82cf-984464319d42.png)
![image](https://user-images.githubusercontent.com/54974019/103929622-8b3dff00-5158-11eb-8efc-89f9a866a52a.png)
否者总是报错
![image](https://user-images.githubusercontent.com/54974019/103929837-d3f5b800-5158-11eb-86d1-2f7d01be68ab.png)

**Comment by danielwii** [comment]
@EdmodoYunjiang 直接使用 `barrageWallController.send(List<Bullet> bullets)` 可以吗？
