### ISSUE TITLE
有一个报错

### ISSUE THREAD

**Issue by Seifon** [danielwii/flutter_barrage#2]
Because every version of flutter_test from sdk depends on quiver 2.0.1 and every version of flutter_barrage depends on quiver ^2.0.2, flutter_test from sdk is incompatible with flutter_barrage.
So, because mystery_live depends on both flutter_barrage any and flutter_test any from sdk, version solving failed.

**Comment by danielwii** [comment]
May I have your `flutter doctor -v` info? I am in the beta channel, the flutter_test is using quiver 2.0.2.

**Comment by danielwii** [comment]
or try dependency overwrite:
```yaml
dependency_overrides:
  quiver: ^2.0.1
```
