### ISSUE TITLE
弹幕堆叠问题

### ISSUE THREAD

**Issue by forJrking** [danielwii/flutter_barrage#20]
massiveMode: false, true 都出现弹幕堆叠问题。有什么解决方法么

**Comment by danielwii** [comment]
https://github.com/danielwii/flutter_barrage/issues/3#issuecomment-759920796

**Comment by danielwii** [comment]
#3

**Comment by forJrking** [comment]
> 可以查看这里看能否解决：[#3 (comment)](https://github.com/danielwii/flutter_barrage/issues/3#issuecomment-759920796)

设置maxBulletHeight: 60.0 还是不能解决，一开始很正常，如果点击一个弹幕跳转其他路由，返回此页面，弹幕就堆叠了

**Comment by danielwii** [comment]
try v0.5.2
