### ISSUE TITLE
恳请大佬升级flutter2和空安全！

### ISSUE THREAD

**Issue by lan2000** [danielwii/flutter_barrage#21]
恳请大佬升级flutter2和空安全！

**Comment by danielwii** [comment]
最近一直在另外一个项目上，有需要的话我近期排上日程。

**Comment by danielwii** [comment]
#22 方便的话可以用该分支测试一下。

**Comment by danielwii** [comment]
try [0.5.0-nullsafety.0](https://pub.dev/packages/flutter_barrage/versions/0.5.0-nullsafety.0)
