### ISSUE TITLE
flutter pub get failed

### ISSUE THREAD

**Issue by oloshe** [danielwii/flutter_barrage#24]
Because flutter_barrage >=0.4.4 <0.5.0-nullsafety.0 depends on quiver ^2.1.5 and sortedmap 0.5.1 depends on quiver ^3.0.0, flutter_barrage >=0.4.4 <0.5.0-nullsafety.0 is incompatible with sortedmap 0.5.1.
So, because voice_flutter depends on both sortedmap 0.5.1 and flutter_barrage ^0.4.6, version solving failed.

**Comment by danielwii** [comment]
Can you use version [0.5.0-nullsafety.0](https://pub.dev/packages/flutter_barrage/versions/0.5.0-nullsafety.0)?

**Comment by danielwii** [comment]
It's a prerelease version and I will publish `0.5.1` later.
