### ISSUE TITLE
A problem about Flutter sdk version 

### ISSUE THREAD

**Issue by yongjieYuan** [danielwii/flutter_barrage#25]
这个插件现在是支持到了flutter 2.10了；
我项目用的是2.5.3的，如果手改yaml文件的依赖，这个插件也是可以支持2.5.3的吧……
感觉这个插件版本支持的有点高【捂脸】

**Comment by danielwii** [comment]
现在是在 flutter 3.0.2，dart 是 ">=2.16.2 <3.0.0" 下构建的。
你现在用的版本是 null-safety 的吗？如果不是可以试试使用 `[0.4.6](https://pub.dev/packages/flutter_barrage/versions/0.4.6)` 这个版本，0.5 就是专门改的 null-safety。

**Comment by danielwii** [comment]
@yongjieYuan 项目不大的话可以升级到 flutter3 的，null-safety 熟悉的话还是可以减少很多空指针异常的，现在各个插件基本上也都支持了。我自己的项目就是专门花了一天时间切换过来的。

**Comment by danielwii** [comment]
没有问题的话我先关闭这个了，使用上再有什么问题再问我。
