### ISSUE TITLE
每条弹幕可以不重叠吗 

### ISSUE THREAD

**Issue by herowws** [danielwii/flutter_barrage#26]
![57018a51c7b280bd14ee85dcdfaf3b8](https://user-images.githubusercontent.com/41428542/178917802-c0708ea4-ef5c-4a95-a35e-a42764ea7b61.jpg)
![image](https://user-images.githubusercontent.com/41428542/178917891-1e500932-4bd5-4419-8430-d1caf2de8f3e.png)

**Comment by danielwii** [comment]
参数中有一个是关闭海量模式，在通道全部占用的时候会丢弃弹幕。

**Comment by danielwii** [comment]
try v0.5.2
