### ISSUE TITLE
barrage text appear overlapping

### ISSUE THREAD

**Issue by Seifon** [danielwii/flutter_barrage#3]
barrage text appear overlapping

弹幕里的文字会重叠

**Comment by danielwii** [comment]
默认是会重叠的，今天我会发布一个新的版本，包括增加一个海量模式的开关，关闭的时候弹幕不会重叠，弹幕数量过多没法显示的时候会丢失弹幕。

**Comment by danielwii** [comment]
#5

**Comment by Seifon** [comment]
如果开启了海量模式，但是弹幕数量很少的情况下，还会出现重叠现象吗？

**Comment by danielwii** [comment]
理论上应该不会。
海量模式的区别在于没有可用的通道的时候会不会被丢弃。

**Comment by Seifon** [comment]
那挺好的，我晚上试试看

**Comment by Seifon** [comment]
还是有一点小问题。我send(Text(color: colors.white)); 发送的弹幕是一个白色的文本，可是弹幕发射出来，有的是白色，有的是黑色额

**Comment by danielwii** [comment]
能截图看一下吗？

**Comment by Seifon** [comment]
barrageWallController.send([
      new Bullet(
          child: Text(
        bulletScreenContent.content,
        style: TextStyle(color: Colors.white),
      ))
    ]);

**Comment by Seifon** [comment]
稍等一下，我截图看看看

**Comment by Seifon** [comment]
http://tva1.sinaimg.cn/large/006COV1Agy1g3001rs0l2j30wu0dc77o.jpg

**Comment by danielwii** [comment]
我创建了一个 gitter.im，你可以在项目首页找到 badge，方便的话在那里说吧，还有些问题需要确认下。

**Comment by Seifon** [comment]
没有找到啊

**Comment by Seifon** [comment]
弹幕刚开始会出现黑色字体，发射一会后，就没有黑色字体了

**Comment by danielwii** [comment]
https://gitter.im/flutter_barrage/community

**Comment by Seifon** [comment]
昨天的版本没有这个问题，要不你对比一下改动代码看看

**Comment by Wing-Li** [comment]
massiveMode 不论设置为 true 还是 false ，弹幕依然还是会覆盖啊。

**Comment by danielwii** [comment]
@Wing-Li 原理就是通过 maxBulletHeight 来计算出可用的 channel。最近使用者不少，之后我再完善下文档，详细说明下。

**Comment by Wing-Li** [comment]
> @Wing-Li 原理就是通过 maxBulletHeight 来计算出可用的 channel。最近使用者不少，之后我再完善下文档，详细说明下。

挺棒的，感觉 Flutter 库里能找到的弹幕插件，就只有你这个可以用。其余的或多或少都不完善。

**Comment by danielwii** [comment]
@Wing-Li 感谢分享和 star。

**Comment by 343863527** [comment]
我设置了maxBulletHeight依然会重叠啊

**Comment by danielwii** [comment]
@343863527 你可以在 examples 下面加个复现的例子吗？或者单独做个复现的库，我上去看下。

**Comment by InTheClodus** [comment]
其实问题出现在showTime 这个方法上，因为用的是随机数，所以只要随机数多了，就容易出现重复的数字就会导致重复，
我尝试写这个方法来过滤重复的随机数，但是效果不是很好

```dart
  /// 用于记录已经存在的数据
  List<int> resultList = [];
  final _random = Random();

  int next2(int min, int max) {
    /// 如果不存在当前的实际则直接返回，并添加防止下回随到
    if (!resultList.contains(min + _random.nextInt(max - min))) {
      resultList.add(min + _random.nextInt(max - min));
      return min + _random.nextInt(max - min);
    } else {
      /// 稍微调整随机数，使得更随机
      return min +
          _random.nextInt(
              (max + _random.nextInt(min)) - (min - _random.nextInt(min)));
    }
  }
```
```dart
next2(1, 100000)
```
代替
```dart
random.nextInt(60000)
```

**Comment by danielwii** [comment]
你说的 showTime 方法是指哪个？
目前该项目的原理是通过高度分割出了若干个弹幕通道，海量模式作为一个开关用于约定弹幕过多时的表现方式。
即所有通道都已被弹幕占用时开启海量会继续显示从而覆盖之前的某个弹幕，关闭海量模式则会丢弃无可用通道用于显示的弹幕。

**Comment by InTheClodus** [comment]
> 你说的 showTime 方法是指哪个？ 海量模式作为一个开关用于约定两种显示弹幕的模式：
> 
> * 关闭海量模式。通过高度分割出了若干个弹幕通道，弹幕通过一个随机数落在某个通道中，无可用通道时丢弃。
> * 开启海量模式。直接随机位置输出弹幕。

```dart
      final showTime = random.nextInt(60 * 60 * 1000);
      return Bullet(
        showTime: showTime,
//        child: Text('$i-$showTime'),
        child: IgnorePointer(child: Text('$i-$showTime')),
      );
```
Bullet下的这个showTime，随机数随出来的时间一样的情况下，弹幕就会出现堆叠的情况

**Comment by danielwii** [comment]
这是示例中的代码，这个`showTime`的概念对应的是你的视频中的具体的一个时间戳。
这里用随机值只是生成了一些测试的弹幕。

**Comment by InTheClodus** [comment]
> 这是示例中的代码，这个`showTime`的概念对应的是你的视频中的具体的一个时间戳。 这里用随机值只是生成了一些测试的弹幕。

这样子，然而，我有个项目客户要求有弹幕，但是后台给我返回的就一个字符串列表，所以我这里只能用随机数

**Comment by danielwii** [comment]
是在视频或音频上的话用该视频或音频当前播放的时间戳就行了。

**Comment by InTheClodus** [comment]
> 是在视频或音频上的话用该视频或音频当前播放的时间戳就行了。

我们是在一张图片上方显示的，没有视频和音频那些 (✘_✘)

**Comment by danielwii** [comment]
哦，明白了，那这是个产品设计问题了。。。试试海量模式？让它随机显示就可以了。
