### ISSUE TITLE
在播放视频时，如果回退进度条，那么在这段时间之前的弹幕会全部消失。

### ISSUE THREAD

**Issue by Syngou** [danielwii/flutter_barrage#31]
首先感谢您的开源项目，本人在使用弹幕库时出现了以下问题，希望能够解决，感激不尽。
- 使用 `timelineNotifier` 与视频进度同步。
- 播放视频时回退进度条（如当前为 `5：00`， 回退后为 `3: 00`)
- 结果 `5:00` 之前的弹幕全部消失，直到 视频重新播放到 `5:00`时弹幕才重新出现。

**Comment by danielwii** [comment]
试一下最新的分支是否可以满足需求。

**Comment by Syngou** [comment]
可以了，感谢！

**Comment by danielwii** [comment]
release 0.5.4
