### ISSUE TITLE
请问大佬 有没有实现过在视频播放器上叠加弹幕

### ISSUE THREAD

**Issue by shenqidebaozi** [danielwii/flutter_barrage#7]
如踢

**Comment by danielwii** [comment]
写这个的时候就是为了在视频上加弹幕的，flutter_barrage 自己有一个时间轴，可以通过 timelineNotifier 来和视频的时间轴同步。其实就是在接收到视频的 position 信息的时候再通过 timelineNotifier 来更新弹幕墙的时间轴。
```dart
// 定义一个 timelineNotifier
ValueNotifier<BarrageValue> timelineNotifier = ValueNotifier(BarrageValue());
// 传入 barrageWall
BarrageWall(
  timelineNotifier: timelineNotifier,
  ...,
```
假如使用 [video_player](https://github.com/flutter/plugins/tree/master/packages/video_player)
```dart
// 在 video_player 上加一个 listener 来更新弹幕墙的 timeline。
controller.addListener(() {
  timelineNotifier.value = timelineNotifier.value.copyWith(
    timeline: controller.value.position.inMilliseconds,
    isPlaying: controller.value.isPlaying,
  );
});
```
有什么问题可在 gitter 中直接提问，另外之后我会写一个 example 和集成文档。

**Comment by shenqidebaozi** [comment]
已经叠加到视频播放器上面了,现在在研究如何在播放器上添加一个发送弹幕的按钮

**Comment by shenqidebaozi** [comment]
另外是否可以增加控制弹幕顶部 顶部 全屏显示的选项呢?

**Comment by shenqidebaozi** [comment]
希望大佬出一个弹幕播放器,嘿嘿嘿,懒是第一生产力

**Comment by danielwii** [comment]
> 已经叠加到视频播放器上面了,现在在研究如何在播放器上添加一个发送弹幕的按钮

关于这个我也考虑过，你可以在绘制的播放器上放一个按钮，也可以在播放器外面放一个输入框。

> 另外是否可以增加控制弹幕顶部 顶部 全屏显示的选项呢?

你说的是类似 bilibili 那个顶部、底部弹幕吧，这个功能也在考虑中，基本上未来的功能都会按照 bilibili 增加。

> 希望大佬出一个弹幕播放器,嘿嘿嘿,懒是第一生产力

其实已经有一个了，不过就是照着 flutter 的 video_player 来写的，但是目前处于非常早期的测试阶段。另外这个和视频播放器集成起来还是非常容易的，只要套在外面就行了。

**Comment by danielwii** [comment]
[chewie example](https://github.com/danielwii/flutter_barrage/blob/master/example/lib/chewie.dart)
